### PR TITLE
Add hat support for joysticks.

### PR DESCRIPTION
**Pull request by pbos**
I have an arcade controller that doesn't support x/y analog axis, I think this would make it able to work with `rrootage`, but I haven't been able to build with MSVC successfully, do you have build instructions anywhere / could you make a build with this patch applied?

### CODE REVIEW

**Comment by abagames** [comment]
I added [how to build section](https://github.com/abagames/rrootage/tree/master#how-to-build) to README. Would you try to build with MSYS2?

**Comment by abagames** [comment]
I think (hat | SDL_HAT_RIGHT) should be  (hat & SDL_HAT_RIGHT) .

**Comment by pbos** [comment]
Agreed, I think you merged a broken version. Can you revert it?

I almost got mingw32 building yesterday but hit some linking issues, hopefully I can have it running this weekend.

**Comment by abagames** [comment]
I fixed these problems before merging. Is that ok?
[Merge branch 'pbos-add_joystick_hat_support'](https://github.com/abagames/rrootage/commit/888d8fc717bf81ec57571f0578262112d45877c7)

**Comment by pbos** [comment]
Ah, I didn't see that you made modifications in the merge commit. That looks alright. If you make a build I can test it, otherwise I'll try to get my build environment running again. Thanks!

**Comment by pbos** [comment]
I just saw that you built `rr.exe` and had it checked in. This now has supports the arcade joystick I have connected. I got building to work up until linking of `libbulletml.a` (which is built against another SDK version). I'll try to get that rebuilt from source so that I can link.

```
$ make
g++ -o rr.exe rr.o foe.o foecommand.o barragemanager.o boss.o ship.o laser.o frag.o background.o letterrender.o shot.o screen.o vector.o degutil.o rand.o mt19937int.o soundmanager.o attractmanager.o rr_res.o -static-libgcc -static-libstdc++ -Wl,-Bstatic,--whole-archive -lwinpthread -Wl,--no-whole-archive -lglu32 -lopengl32 -lmingw32 -L/usr/lib -lSDLmain -L. -lbulletml -Wl,-Bdynamic -L.. -lSDL -lSDL_mixer -mwindows
.\libbulletml.a(calc.o):calc.cpp:(.text+0x391): undefined reference to `_imp____acrt_iob_func'
collect2.exe: error: ld returned 1 exit status
```

**Pull request merged**
