### PR TITLE
Upgraded build system to run cmake and build on modern windows.

### LINKED ISSUE #7: Modernizing the game libraries and build (PR discussion)
As part of a port to nintendo switch of the game, i have modernized the game so that it works well in there. There is a series of improvements ive done that i can PR back to the project, but i want to discuss them a bit before, to see what would fit.

* CMake or Premake build: Original makefiles are tricky to get working on windows, and very tricky to get working for cross compilation. For the port i made the game work fine on Premake, and i also could PR it as CMake given there isnt much difference, i only use premake because it works better for cross compilation.
* Upgrading SDL to SDL2: Original SDL 1 is not supported on Switch, so i upgraded it to SDL2.  As the project only uses SDL for input, audio, and windowing, its a small change. 
* SDL Gamepad api: With the change to SDL 2, i also changed the input to support the Gamepad api instead of the Joystick api. This gives native support for Xbox gamepads.
* Embedding BulletML inside the project itself. Makes it much easier to build from scratch.
* Removal of Boost: No longer needed as shared_ptr is a cpp11 thing.
* Removal of auto_ptr: Like above, i changed it to use cpp11 shared_ptr instead.
* std::filesystem (cpp17) instead of dirint to load the bullet description files. This makes the code more portable, but cpp17 is a bit too new.
* Replacing SDL_Mixer by using SDL audio directly and loading the ogg files with stb_vorbis.
* Changed opengl to use Glad (dynamic function loading). 
* Opengl Optimization: The fixed pipeline opengl of the project can perform slow on modern machines. Ive optimized the bullet related graphics to perform sorting and batch-rendering, this improves the render speed of bullets by multiple times, making the game never slowdown unless its drawing 600+ bullets. Im still working on this, there is a slight difference in graphics due to the different render orders of the bullets. My goal is to have the game without any slowdown on nintendo switch.
This also is a big difference to gameplay, as there is now no slowdown to help you navigate when the screen is full of bullets. 

With the set of fixes, building the project would be a single click process using cmake, Only having to point Cmake to your SDL2 folder. On windows it runs fully native without having to use  MinGW

The code is on my personal fork, but that version is experimental and its missing necesary files due to nintendo switch SDK being NDA'd. The code that would be on a PR would be a cleaned version of that.

### PR DESCRIPTION
**Pull request by vblanco20-1**
Build system moved into CMake. To build, just run cmake and make sure to set the SDLMIXER_PATH and SDL_PATH variables so that it can find SDL.

The cmake build files default to win64. I dont have linux so i cant check what to fix to make them build on linux.

Boost removed from bullet ML, code builds on Cpp14 now. boost::shared_ptr is swapped with std::shared_ptr

BulletML embedded into the project.

Dirint swapped with a windows capable version from https://github.com/tronkko/dirent (mit license). Removes the need for minGW.

The PR only changes the build, game code is left as-is, no changes to anything.

The PR is unfinished, i want to fix it to also build linux before it should get merged.

Ive created this commit as a release, so that its possible to try the compiled version https://github.com/vblanco20-1/rrootage/releases/tag/pr0.1

### CODE REVIEW

**Comment by vblanco20-1** [comment]
Updated: I ported everything to work on Linux (ubuntu) by using github actions. Linux version will be built automatically in actions, but i cant run it for testing myself.

**Comment by vblanco20-1** [comment]
Made the scripts automatically download SDL. This makes the project 1-click-compile on windows, and on linux you just apt-get the SDL libs. Too bad git decided to un-squash the commits.

**Comment by abagames** [comment]
Do I need to install Visual Studio Community 2019 or something similar in order to build this code with CMake?

**Comment by vblanco20-1** [comment]
@abagames  Doesnt have to be the latest VS, 2017 would also work. To make it work you need to use the standalone cmake to generate a VS project. Its also possible to get it working on visual studio code if you have the cmake extension installed. Then you can open the project directly in Vscode and get it building. 
 The cmake script is configured to build in 64 bit and 32 bit.

The executable will be added to the cmake build folder you specified, and gotta copy the DLLs there manually. (the new DLLs, not the current ones on the root of the project which are old ones). The binaries will be generated under the folder build/bin/Debug/ (or Release). And SDL and mixer are downloaded under the build/libs folder, to grab the DLLs from them.

**Comment by abagames** [comment]
I am not familiar with CMake, can you tell me how to build rr.exe? I installed Build Tools for Visual Studio 2019 and ran 'cmake .' in the root directory of the repository. Some files were generated, but rr.exe does not seem to be generated.

**Comment by vblanco20-1** [comment]
I generally use the cmake GUI, but if you want touse the commandline, you can use the commands that the CI pipeline in github actions use, which are:
```
cmake -DCMAKE_BUILD_TYPE=Release
cmake --build . --config Release
```
From the root folder of the project. That should compile rr.exe under the /bin/Release/folder. Should be completely automatic, dependencies like SDL are automatically installed.

If you want to use the GUI instead (to edit parameters more easily, like build folder), then you can check this part of the vulkan tutorial i wrote. The scripts used for that tutorial are similar to the ones i used here, except they install SDL automatically. https://vkguide.dev/docs/chapter-0/building_project/

Keep in mind the rr.exe will default to 64 bit build, and will need the 64 bit DLLs. The SDL dlls are autodownloaded on the "libs" folder

**Comment by abagames** [comment]
I entered the above command, but I got the following error. (It is inconvenient that the tool is localized so that messages are written in Japanese.)

```
libucrt.lib(_file.obj) : error LNK2005: _iob は既に barragemanager.cc.obj で定義されています。
-- snip ---
SDLmain.lib(SDL_win32_main.obj) : error LNK2019: 未解決の外部シンボル __imp_remove が関数 cleanup_output で参照されまし た
SDLmain.lib(SDL_win32_main.obj) : error LNK2019: 未解決の外部シンボル __imp_setbuf が関数 redirect_output で参照されました
SDLmain.lib(SDL_win32_main.obj) : error LNK2019: 未解決の外部シンボル __imp_freopen が関数 redirect_output で参照されま した
```

The following is a translation into English.

```
libucrt.lib(_file.obj) : error LNK2005: _iob is already defined at barragemanager.cc.obj
-- snip ---
SDLmain.lib(SDL_win32_main.obj) : error LNK2019: undefined external symbol __imp_remove is referenced at cleanup_output
SDLmain.lib(SDL_win32_main.obj) : error LNK2019: undefined external symbol __imp_setbuf is referenced at redirect_output
SDLmain.lib(SDL_win32_main.obj) : error LNK2019: undefined external symbol __imp_freopen is referenced at redirect_output
```

Is there anything you can think of as a solution? Do I need to do something like 'make clean'?

**Comment by vblanco20-1** [comment]
@abagames  I havent seen that error with `libucrt.lib`. How exactly are you trying to compile it? And on what windows version. Can you try using the CMake gui? In there you can select what compiler and architecture to use. Maybe if you are doing cmake through commandline by default its selecting a minGW compiler.

With CMakegui, you have to set source code folder, then build folder, and then click Configure and then Generate to create VS project.
image

**Comment by abagames** [comment]
I understood.
1. Use cmake-gui to generate the .sln file and other necessary files in the `build` directory.
1. Open the `rRootage.sln` file using Visual Studio Community 2019.
1. Build it.
1. `rR.exe` is generated in the `bin/Release` directory.
1. Copy the dlls needed for execution from the `libs` directory.
1. Copy the sounds directory and other necessary resources.
1. Run `rR.exe`.

With these steps I was able to build and run `rR.exe`.
I would like to keep the original build method using MSYS2 in the master branch. Therefore, I will create a new branch named `cmake` and merge this PR into it.

**Comment by vblanco20-1** [comment]
Im going to see if i can improve the cmake file a bit to make it easier. Should the .exe be generated in the root folder? That can be automatically done.

**Comment by abagames** [comment]
I think it would be easier to build and run if all the necessary exe and dll files were placed in the root folder.

**Comment by vblanco20-1** [comment]
Very well ill go modify it for that

**Comment by vblanco20-1** [comment]
@abagames  I tried a few ways, but wasnt happy with the result due to MSVC doing MSVC things. At the end, ive added a copy command to the build script.

The executable will be created under the /bin/ folder, but after it compiles rr.exe, it will copy it into root folder automatically. It will also copy the DLLs. Only does the DLL copy on windows, on linux some of those DLLs might just be on system paths. The .exe is copied on both platforms. 

Let me know if thats alright with you.

**Comment by abagames** [comment]
I was able to confirm that the exe and dll files are copied to the root folder in my environment. If everything is ok, I will merge this PR into the cmake branch.

**Comment by abagames** [comment]
I'm also planning to add a brief description of how to build with cmake in the README.

**Pull request merged**
